### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by hall13** [BenExile/Dropbox#82]
Hello,

I am trying to get a file from my dropbox and this error keeps coming up.  

Fatal error: Uncaught exception 'Dropbox\Exception' with message 'Forbidden' in C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\umf\freight\Dropbox\Dropbox\OAuth\Consumer\Curl.php:153 Stack trace: #0 C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\umf\freight\Dropbox\Dropbox\API.php(495): Dropbox\OAuth\Consumer\Curl->fetch('GET', 'https://api-con...', 'files/sandbox/C...', Array) #1 C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\umf\freight\Dropbox\Dropbox\API.php(237): Dropbox\API->fetch('GET', 'https://api-con...', 'files/sandbox/C...', Array) #2 C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\umf\freight\Dropbox\examples\getFile.php(25): Dropbox\API->getFile('test.pdf') #3 {main} thrown in C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\umf\freight\Dropbox\Dropbox\OAuth\Consumer\Curl.php on line 153

**Comment by BenExile** [comment]
Please refer to the Dropbox API documentation which states the following for 403 errors:

"Bad OAuth request (wrong consumer key, bad nonce, expired timestamp...). Unfortunately, re-authenticating the user won't help here"

Can you please confirm if this happens for all files? Also please provide the entire failed request, removing your consumer key/secret.

**Comment by hall13** [comment]
It happens for all the examples except accountInfo.php.  For the other ones this gets output every time.

Fatal error: Uncaught exception 'Dropbox\Exception' with message 'Forbidden' in C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\umf\freight\Dropbox\Dropbox\OAuth\Consumer\Curl.php:153 Stack trace: #0 C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\umf\freight\Dropbox\Dropbox\API.php(495): Dropbox\OAuth\Consumer\Curl->fetch('GET', 'https://api-con...', 'files/sandbox/C...', Array) #1 C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\umf\freight\Dropbox\Dropbox\API.php(237): Dropbox\API->fetch('GET', 'https://api-con...', 'files/sandbox/C...', Array) #2 C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\umf\freight\Dropbox\examples\getFile.php(25): Dropbox\API->getFile('Copy of JoeKeni...') #3 {main} thrown in C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\umf\freight\Dropbox\Dropbox\OAuth\Consumer\Curl.php on line 153

My consumer key and secret work, because if they didn't then would accountInfo.php not work?

**Comment by tippatone** [comment]
Hi,
I'm getting the same Fatal Errors. Like hall13 said, the only one that works for me is accountInfo.php

Fatal error: Uncaught exception 'Dropbox\Exception' with message 'Forbidden' in C:\xampp\htdocs\drop\Dropbox\OAuth\Consumer\Curl.php:153 Stack trace: #0 C:\xampp\htdocs\drop\Dropbox\API.php(495): Dropbox\OAuth\Consumer\Curl->fetch('GET', 'https://api-con...', 'files/sandbox/a...', Array) #1 C:\xampp\htdocs\drop\Dropbox\API.php(237): Dropbox\API->fetch('GET', 'https://api-con...', 'files/sandbox/a...', Array) #2 C:\xampp\htdocs\drop\examples\getFile.php(25): Dropbox\API->getFile('api_upload_test...', false) #3 {main} thrown in C:\xampp\htdocs\drop\Dropbox\OAuth\Consumer\Curl.php on line 153
